---
- hosts: all
  user: ansible
  sudo: yes

  vars:
    ssh_users:
    - name: thiagocaiubi
    - name: gallois

  roles:
    - common
    - users
    - git
    - redis
    - nodejs
    - forever
    - act-acdc
