---
- hosts: all
  user: ansible
  sudo: yes

  vars:
    ssh_users:
      - name: thiagocaiubi
      - name: gallois
    redis_instances:
      - port: 7500
        maxmemory: 100mb

  roles:
    - common
    - users
    - redis
