---
- hosts: all
  user: ansible
  sudo: yes

  vars:
    ssh_users:
      - name: thiagocaiubi
        key: "{{ lookup('file', 'thiagocaiubi.pub') }}"
      - name: gallois
        key: "{{ lookup('file', 'gallois.pub') }}"
    redis_instances:
      - port: 7500
        maxmemory: 100mb

  roles:
    - common
    - users
    - redis
