---
- name: Create users
  user: name={{ item.name }} shell=/bin/bash
  with_items: ssh_users

- name: Add key to users
  authorized_key: user={{ item.name }} key="{{ lookup('file', '{{ item.name }}.pub') }}"
  with_items: ssh_users

- name: Copy sudoers file for safety
  command: cp -f /etc/sudoers /etc/sudoers.tmp

- name: Create sudoers file backup
  command: cp -f /etc/sudoers /etc/sudoers.${date}.bak

- name:  Add users to sudoers
  lineinfile: dest=/etc/sudoers.tmp state=present regexp="^{{ item.name }} ALL\=\(ALL\) NOPASSWD:ALL" line="{{ item.name }} ALL=(ALL) NOPASSWD:ALL"
  with_items: ssh_users

- name: Copy sudoers file
  shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers
